import{useState,useEffect}from"react";
import{supabase}from"./supabase";
import{DISTRICT_LIST,SAUDI_CITIES,calcGeoScore,ZONE_COLORS}from"./geoScoring";
const STEPS=[{id:1,icon:"👤",ar:"তথ্য"},{id:2,icon:"🏍️",ar:"লাইসেন্স"},{id:3,icon:"📄",ar:"নথি"},{id:4,icon:"🔧",ar:"দক্ষতা"},{id:5,icon:"🧠",ar:"আচরণ"},{id:6,icon:"✅",ar:"নিশ্চিত"}];
const INIT={full_name:"",whatsapp:"",location:"",age:"",height_cm:"",weight_kg:"",passport_or_iqama:"",marital_status:"",children_count:"",has_license:"",licenseFile:null,photoFile:null,iqamaFile:null,passportFile:null,car_wash_description:"",videoFile:null,q1:"",q2:"",q3:"",q4:"",q5:"",q6:"",declaration:false,bangladesh_district:"",bangladesh_city:"",map_link:"",saudi_city:"",ready_for_riyadh:""};
const CC=[{c:"+880",f:"🇧🇩",a:"BD"},{c:"+966",f:"🇸🇦",a:"SA"},{c:"+971",f:"🇦🇪",a:"AE"},{c:"+965",f:"🇰🇼",a:"KW"},{c:"+974",f:"🇶🇦",a:"QA"},{c:"+973",f:"🇧🇭",a:"BH"},{c:"+968",f:"🇴🇲",a:"OM"}];
function PhoneF({form,set,errors}){const[cc,setCc]=useState("+880");const[num,setNum]=useState("");useEffect(()=>{if(num)set("whatsapp",`${cc}${num}`);else set("whatsapp","");},[cc,num]);return(<div style={{display:"flex",gap:8,direction:"ltr"}}><select value={cc} onChange={e=>setCc(e.target.value)} style={{...s.inp,width:110,flex:"0 0 auto",direction:"ltr",textAlign:"left",padding:"12px 8px",...(errors.whatsapp?s.err:{})}}>{CC.map(c=><option key={c.c} value={c.c}>{c.f} {c.c}</option>)}</select><input type="tel" value={num} onChange={e=>setNum(e.target.value.replace(/\D/g,""))} placeholder="XXXXXXXXXX" dir="ltr" style={{...s.inp,flex:1,direction:"ltr",textAlign:"left",...(errors.whatsapp?s.err:{})}}/></div>);}
export default function ApplicantForm({onBack}){
  const[step,setStep]=useState(1);const[form,setForm]=useState(INIT);const[errors,setErrors]=useState({});const[submitting,setSubmitting]=useState(false);const[prog,setProg]=useState(0);const[done,setDone]=useState(false);const[anim,setAnim]=useState(true);
  const set=(k,v)=>setForm(p=>({...p,[k]:v}));
  const go=n=>{setAnim(false);setTimeout(()=>{setStep(n);setAnim(true);},80);};
  const validate=()=>{const e={};
    if(step===1){if(!form.full_name.trim())e.full_name=1;if(!form.whatsapp.trim())e.whatsapp=1;if(!form.location)e.location=1;if(!form.age||+form.age<25||+form.age>38)e.age=1;if(!form.height_cm||+form.height_cm<167)e.height_cm=1;if(!form.weight_kg||+form.weight_kg<55||+form.weight_kg>90)e.weight_kg=1;if(!form.passport_or_iqama.trim())e.passport_or_iqama=1;if(!form.marital_status)e.marital_status=1;if(!form.bangladesh_district)e.bangladesh_district=1;if(!form.bangladesh_city.trim())e.bangladesh_city=1;if(form.location==="inside_ksa"&&!form.saudi_city)e.saudi_city=1;if(form.location==="inside_ksa"&&!form.ready_for_riyadh)e.ready_for_riyadh=1;}
    if(step===2){if(!form.has_license)e.has_license=1;}
    if(step===3){if(!form.photoFile)e.photoFile=1;if(form.location==="inside_ksa"&&!form.iqamaFile)e.iqamaFile=1;if((form.location==="outside_bangladesh"||form.location==="outside_other")&&!form.passportFile)e.passportFile=1;}
    if(step===4){if(!form.car_wash_description.trim())e.car_wash_description=1;if(!form.videoFile)e.videoFile=1;}
    if(step===5){["q1","q2","q3","q4","q5","q6"].forEach(k=>{if(!form[k].trim())e[k]=1;});}
    if(step===6){if(!form.declaration)e.declaration=1;}
    setErrors(e);return!Object.keys(e).length;};
  const next=()=>{if(validate())go(Math.min(step+1,6));};
  const back=()=>{if(step===1&&onBack)onBack();else go(Math.max(step-1,1));};
  const upload=async(file,bucket,path)=>{try{await supabase.storage.from(bucket).upload(path,file,{upsert:true});const{data}=supabase.storage.from(bucket).getPublicUrl(path);return data.publicUrl;}catch(e){return null;}};
  const submit=async()=>{if(!validate())return;setSubmitting(true);
    try{
      const uid=crypto.randomUUID();setProg(15);
      const photoUrl=form.photoFile?await upload(form.photoFile,"applicant-photos",`${uid}/photo.jpg`):null;setProg(35);
      const videoUrl=form.videoFile?await upload(form.videoFile,"applicant-videos",`${uid}/video.mp4`):null;setProg(60);
      const licUrl=(form.has_license==="yes"&&form.licenseFile)?await upload(form.licenseFile,"applicant-licenses",`${uid}/lic.jpg`):null;
      const iqUrl=form.iqamaFile?await upload(form.iqamaFile,"applicant-licenses",`${uid}/iq.jpg`):null;
      const ppUrl=form.passportFile?await upload(form.passportFile,"applicant-licenses",`${uid}/pp.jpg`):null;
      setProg(80);
      const geoResult=calcGeoScore(form.bangladesh_district);
      const{error}=await supabase.from("applicants").insert({full_name:form.full_name,whatsapp:form.whatsapp,location:form.location,age:+form.age,height_cm:+form.height_cm,weight_kg:+form.weight_kg,passport_or_iqama:form.passport_or_iqama,has_license:form.has_license==="yes",marital_status:form.marital_status,children_count:form.children_count?+form.children_count:0,license_image_url:licUrl,personal_photo_url:photoUrl,driving_video_url:videoUrl,iqama_image_url:iqUrl,passport_image_url:ppUrl,car_wash_description:form.car_wash_description,q1_client_refusal:form.q1,q2_equipment_damage:form.q2,q3_left_previous_job:form.q3,q4_salary_deduction:form.q4,q5_one_year_goal:form.q5,q6_difficult_colleague:form.q6,bangladesh_district:form.bangladesh_district,bangladesh_city:form.bangladesh_city,map_link:form.map_link||null,saudi_city:form.saudi_city||null,ready_for_riyadh:form.ready_for_riyadh||null,geo_score:geoResult?.score||null,status:"pending"});
      if(error)throw error;
      try{await fetch("https://gate.whapi.cloud/messages/text",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer UGIXfm3KoPFjTZgvlQFRFuSbDzGb7BU6"},body:JSON.stringify({to:"966564884419@s.whatsapp.net",body:`🔔 طلب توظيف جديد!\n👤 ${form.full_name} | ${form.age} سنة\n📍 ${form.location==="inside_ksa"?`الرياض: ${form.saudi_city||"—"}`:form.bangladesh_district+" — "+form.bangladesh_city}\n${form.location==="inside_ksa"?`✈️ مستعد للرياض: ${form.ready_for_riyadh==="yes"?"✅ نعم":"❌ لا"}\n`:""}🏍️ رخصة: ${form.has_license==="yes"?"✅":"❌"} | 📊 نقاط المنطقة: ${geoResult?.score||"—"}\n\n👉 https://db1-sandy.vercel.app/#admin`})});}catch(e){console.log("WA",e);}
      setProg(100);setTimeout(()=>setDone(true),400);
    }catch(err){alert("حدث خطأ: "+err.message);setSubmitting(false);}};
  if(done)return(<div style={s.page}><div style={s.bgO1}/><div style={s.bgO2}/><div style={s.card}><div style={{textAlign:"center",padding:"48px 32px"}}><div style={{width:72,height:72,background:"linear-gradient(135deg,#2E7D32,#1b5e20)",borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontSize:32,fontWeight:900,margin:"0 auto 16px"}}>✓</div><h2 style={{color:"#1e293b",fontSize:22,fontWeight:900,margin:"0 0 8px"}}>ধন্যবাদ!</h2><p style={{color:"#475569",fontSize:13,marginBottom:4}}>৪৮ ঘণ্টার মধ্যে হোয়াটসঅ্যাপে যোগাযোগ করা হবে।</p><p style={{color:"#a8834f",fontSize:12}}>شكراً على تقديمك — سيتم التواصل خلال 48 ساعة عبر واتساب.</p></div></div></div>);
  const pct=((step-1)/5)*100;
  return(
    <div style={s.page}><div style={s.bgO1}/><div style={s.bgO2}/>
      <div style={s.card}>
        <div style={s.hdr}><div style={s.logoM}>🪣</div><div><div style={s.hAr}>আবেদন ফর্ম</div><div style={s.hBn}>استمارة التقديم</div></div></div>
        <div style={{height:5,background:"#fed7aa"}}><div style={{height:"100%",width:`${pct}%`,background:"linear-gradient(90deg,#E8712B,#f59e0b)",transition:"width 0.5s"}}/></div>
        <div style={{display:"flex",alignItems:"center",justifyContent:"center",padding:"12px 16px 6px",gap:0}}>
          {STEPS.map((st,i)=>{const done=st.id<step,active=st.id===step;return(<div key={st.id} style={{display:"flex",alignItems:"center"}}><div style={{width:30,height:30,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,background:active?"#E8712B":done?"#2E7D32":"#f1f5f9",color:active||done?"#fff":"#94a3b8",transition:"all 0.3s",transform:active?"scale(1.1)":"scale(1)",boxShadow:active?"0 4px 12px rgba(232,113,43,0.4)":"none"}}>{done?"✓":st.icon}</div>{i<5&&<div style={{width:18,height:2,background:done?"#2E7D32":"#e2e8f0",transition:"background 0.3s"}}/>}</div>);})}
        </div>
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px 10px"}}>
          <span style={{color:"#E8712B",fontWeight:700,background:"#fff7ed",padding:"2px 10px",borderRadius:20,fontSize:11}}>{step}/6</span>
          <span style={{color:"#1e293b",fontSize:14,fontWeight:800}}>{STEPS[step-1].ar}</span>
        </div>
        <div style={{padding:"4px 20px 8px",opacity:anim?1:0,transform:anim?"translateY(0)":"translateY(8px)",transition:"all 0.2s"}}>
          {step===1&&<S2 form={form} set={set} errors={errors}/>}{step===2&&<S3 form={form} set={set} errors={errors}/>}{step===3&&<S4 form={form} set={set} errors={errors}/>}{step===4&&<S5 form={form} set={set} errors={errors}/>}{step===5&&<S6 form={form} set={set} errors={errors}/>}{step===6&&<S7 form={form} set={set} errors={errors}/>}
        </div>
        {submitting&&(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.7)",backdropFilter:"blur(8px)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:999}}><div style={{background:"rgba(30,41,59,0.95)",borderRadius:24,padding:"32px 40px",textAlign:"center",minWidth:260}}><div style={{width:40,height:40,border:"3px solid rgba(255,255,255,0.2)",borderTopColor:"#E8712B",borderRadius:"50%",margin:"0 auto",animation:"spin 0.8s linear infinite"}}/><div style={{color:"#fff",fontWeight:700,marginTop:16}}>ফাইল আপলোড হচ্ছে...</div><div style={{height:6,background:"rgba(255,255,255,0.15)",borderRadius:4,margin:"12px 0 8px",overflow:"hidden"}}><div style={{height:"100%",background:"#E8712B",borderRadius:4,width:`${prog}%`,transition:"width 0.4s"}}/></div><div style={{color:"#E8712B",fontWeight:700}}>{prog}%</div></div></div>)}
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 20px 20px",borderTop:"1px solid #f1f5f9",gap:10}}>
          <button onClick={back} style={{padding:"12px 16px",background:"#f8fafc",border:"1.5px solid #e2e8f0",borderRadius:14,fontSize:12,fontWeight:700,color:"#475569",cursor:"pointer",flex:1}}>← ফিরে</button>
          {step<6?<button onClick={next} style={{padding:"12px 16px",background:"linear-gradient(135deg,#E8712B,#d4631f)",border:"none",borderRadius:14,fontSize:12,fontWeight:800,color:"#fff",cursor:"pointer",flex:2,boxShadow:"0 4px 14px rgba(232,113,43,0.35)"}}>পরবর্তী ←</button>:<button onClick={submit} disabled={!form.declaration||submitting} style={{padding:"12px 16px",background:"linear-gradient(135deg,#2E7D32,#1b5e20)",border:"none",borderRadius:14,fontSize:12,fontWeight:800,color:"#fff",cursor:"pointer",flex:2,opacity:(!form.declaration||submitting)?0.5:1}}>{submitting?`${prog}% হচ্ছে...`:"জমা দিন ✓"}</button>}
        </div>
      </div>
    </div>
  );
}
function S2({form,set,errors}){
  const geo=form.bangladesh_district?calcGeoScore(form.bangladesh_district):null;
  return(<div style={s.fields}>
    <div><div style={s.lbl}>পূর্ণ নাম <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>الاسم الكامل</div><input value={form.full_name} onChange={e=>set("full_name",e.target.value)} style={{...s.inp,...(errors.full_name?s.err:{})}} placeholder="আপনার পূর্ণ নাম লিখুন"/></div>
    <div><div style={s.lbl}>হোয়াটসঅ্যাপ নম্বর <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>رقم الواتساب</div><PhoneF form={form} set={set} errors={errors}/></div>
    <div><div style={s.lbl}>বর্তমান অবস্থান <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>موقعك الحالي</div><select value={form.location} onChange={e=>set("location",e.target.value)} style={{...s.inp,...(errors.location?s.err:{})}}><option value="">নির্বাচন করুন</option><option value="inside_ksa">সৌদি আরবে</option><option value="outside_bangladesh">বাংলাদেশে</option><option value="outside_other">অন্য দেশে</option></select></div>

    {/* إذا داخل السعودية */}
    {form.location==="inside_ksa"&&<>
      <div><div style={s.lbl}>বর্তমান সৌদি শহর <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>المدينة السعودية الحالية</div><select value={form.saudi_city} onChange={e=>set("saudi_city",e.target.value)} style={{...s.inp,...(errors.saudi_city?s.err:{})}}><option value="">শহর নির্বাচন করুন</option>{SAUDI_CITIES.map(c=><option key={c} value={c}>{c}</option>)}</select></div>
      <div><div style={s.lbl}>রিয়াদে কাজ করতে প্রস্তুত? <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>هل أنت مستعد للعمل في الرياض؟</div>
        <div style={{display:"flex",gap:8}}>
          {[["yes","✅ হ্যাঁ","#2E7D32","#f0fdf4","#86efac"],["no","❌ না","#dc2626","#fff5f5","#fca5a5"]].map(([v,label,c,bg,bc])=><div key={v} onClick={()=>set("ready_for_riyadh",v)} style={{flex:1,padding:"12px",border:`2px solid ${form.ready_for_riyadh===v?c:bc}`,borderRadius:12,cursor:"pointer",background:form.ready_for_riyadh===v?bg:"#fafaf9",textAlign:"center",fontSize:12,fontWeight:700,color:form.ready_for_riyadh===v?c:"#64748b"}}>{label}</div>)}
        </div>
        {errors.ready_for_riyadh&&<div style={{color:"#dc2626",fontSize:11}}>⚠ আবশ্যক</div>}
        {form.ready_for_riyadh==="no"&&<div style={{background:"#fef9c3",border:"1px solid #fcd34d",borderRadius:10,padding:"8px 12px",color:"#854d0e",fontSize:11,marginTop:6}}>⚠️ চাকরিটি শুধু রিয়াদে — নিশ্চিত হয়ে এগিয়ে যান</div>}
      </div>
    </>}

    {/* المنطقة في بنغلادش */}
    <div style={{background:"#eff6ff",border:"1px solid #93c5fd",borderRadius:12,padding:"12px 14px"}}>
      <div style={{color:"#1d4ed8",fontSize:12,fontWeight:800,marginBottom:10}}>📍 আপনার বাংলাদেশের অবস্থান</div>
      <div style={{display:"flex",flexDirection:"column",gap:10}}>
        <div><div style={s.lbl}>জেলা <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>المحافظة / المنطقة</div>
          <input value={form.bangladesh_district} onChange={e=>set("bangladesh_district",e.target.value)}
            style={{...s.inp,...(errors.bangladesh_district?s.err:{})}}
            placeholder="যেমন: Kishoreganj, Cumilla, Dhaka..."/>
          {geo&&<div style={{marginTop:6,padding:"8px 12px",borderRadius:10,background:ZONE_COLORS[geo.zone].bg,border:`1px solid ${ZONE_COLORS[geo.zone].border}`}}><div style={{color:ZONE_COLORS[geo.zone].text,fontSize:11,fontWeight:700}}>{ZONE_COLORS[geo.zone].label}</div><div style={{color:ZONE_COLORS[geo.zone].text,fontSize:11,marginTop:2}}>স্কোর: {geo.score}/100</div>{geo.instant_reject&&<div style={{color:"#dc2626",fontSize:11,fontWeight:700,marginTop:4}}>⚠️ ঝুঁকিপূর্ণ — আবেদন প্রত্যাখ্যান হবে</div>}</div>}
        </div>
        <div><div style={s.lbl}>শহর/গ্রাম <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>المدينة / القرية</div>
          <input value={form.bangladesh_city} onChange={e=>set("bangladesh_city",e.target.value)} style={{...s.inp,...(errors.bangladesh_city?s.err:{})}} placeholder="যেমন: Brahmanbaria Sadar"/>
        </div>

        {/* رابط الخريطة */}
        <div>
          <div style={s.lbl}>গুগল ম্যাপ লিংক</div>
          <div style={s.lbl2}>رابط موقعك على خرائط جوجل (اختياري)</div>
          <div style={{display:"flex",gap:8,alignItems:"center",marginBottom:8}}>
            <input value={form.map_link||""} onChange={e=>set("map_link",e.target.value)}
              style={{...s.inp,flex:1,direction:"ltr",textAlign:"left",fontSize:11}}
              placeholder="https://maps.google.com/..."/>
            <a href={`https://maps.google.com/maps?q=${encodeURIComponent((form.bangladesh_city||"")+" "+(form.bangladesh_district||"")+" Bangladesh")}`}
              target="_blank" rel="noreferrer"
              style={{flexShrink:0,padding:"11px 12px",background:"linear-gradient(135deg,#2563eb,#1d4ed8)",borderRadius:10,color:"#fff",fontSize:11,fontWeight:700,textDecoration:"none"}}>
              🗺️ খুলুন
            </a>
          </div>
          <div style={{background:"#f0fdf4",border:"1px solid #86efac",borderRadius:8,padding:"8px 12px"}}>
            <div style={{color:"#16a34a",fontSize:11,fontWeight:700,marginBottom:2}}>কীভাবে লিংক পাবেন?</div>
            <div style={{color:"#15803d",fontSize:10,lineHeight:1.8}}>
              ১. Google Maps এ এলাকা খুঁজুন<br/>
              ২. "Share" চাপুন<br/>
              ৩. লিংক কপি করে এখানে বসান<br/>
              <span style={{color:"#78716c",display:"block",marginTop:2}}>افتح Google Maps وابحث عن منطقتك → مشاركة → انسخ الرابط والصقه هنا</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8}}><div><div style={s.lbl}>বয়স *</div><select value={form.age} onChange={e=>set("age",e.target.value)} style={{...s.inp,...(errors.age?s.err:{})}}><option value="">নির্বাচন</option>{Array.from({length:14},(_,i)=>25+i).map(n=><option key={n} value={n}>{n}</option>)}</select></div><div><div style={s.lbl}>উচ্চতা সেমি *</div><select value={form.height_cm} onChange={e=>set("height_cm",e.target.value)} style={{...s.inp,...(errors.height_cm?s.err:{})}}><option value="">নির্বাচন</option>{Array.from({length:24},(_,i)=>167+i).map(n=><option key={n} value={n}>{n}</option>)}</select></div><div><div style={s.lbl}>ওজন কেজি *</div><select value={form.weight_kg} onChange={e=>set("weight_kg",e.target.value)} style={{...s.inp,...(errors.weight_kg?s.err:{})}}><option value="">নির্বাচন</option>{Array.from({length:36},(_,i)=>55+i).map(n=><option key={n} value={n}>{n}</option>)}</select></div></div>
    <div><div style={s.lbl}>পাসপোর্ট/ইকামা নম্বর <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>رقم الجواز أو الإقامة</div><input value={form.passport_or_iqama} onChange={e=>set("passport_or_iqama",e.target.value)} style={{...s.inp,...(errors.passport_or_iqama?s.err:{})}}/></div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><div><div style={s.lbl}>বৈবাহিক অবস্থা *</div><select value={form.marital_status} onChange={e=>set("marital_status",e.target.value)} style={{...s.inp,...(errors.marital_status?s.err:{})}}><option value="">নির্বাচন</option><option value="single">অবিবাহিত</option><option value="married">বিবাহিত</option><option value="divorced">তালাকপ্রাপ্ত</option></select></div>{form.marital_status==="married"&&<div><div style={s.lbl}>সন্তান সংখ্যা</div><select value={form.children_count} onChange={e=>set("children_count",e.target.value)} style={s.inp}><option value="0">নেই</option>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}</option>)}</select></div>}</div>
  </div>);}
function S3({form,set,errors}){const O=[{v:"yes",ar:"نعم — لدي رخصة",bn:"হ্যাঁ ⭐",c:"#2E7D32",bg:"#f0fdf4"},{v:"no_can",ar:"لا — سأستخرجها",bn:"না, নেব",c:"#E8712B",bg:"#fff7ed"},{v:"no_cannot",ar:"لا — لا أستطيع",bn:"না",c:"#94a3b8",bg:"#f8fafc"}];return(<div style={s.fields}><div style={{color:"#1e293b",fontSize:13,fontWeight:800,marginBottom:8}}>আপনার কি মোটরসাইকেল লাইসেন্স আছে? <span style={{color:"#E8712B"}}>*</span><div style={{color:"#a8834f",fontSize:11,fontWeight:400,marginTop:2}}>هل تملك رخصة قيادة دراجة نارية؟</div></div>{O.map(o=><div key={o.v} onClick={()=>set("has_license",o.v)} style={{display:"flex",alignItems:"center",gap:12,padding:"13px 16px",border:`2px solid ${form.has_license===o.v?o.c:"#e2e8f0"}`,borderRadius:14,cursor:"pointer",background:form.has_license===o.v?o.bg:"#fafaf9"}}><input type="radio" checked={form.has_license===o.v} onChange={()=>set("has_license",o.v)} style={{accentColor:o.c}}/><div><div style={{color:"#1e293b",fontSize:13,fontWeight:700}}>{o.bn}</div><div style={{color:"#a8834f",fontSize:11}}>{o.ar}</div></div></div>)}{errors.has_license&&<div style={{color:"#dc2626",fontSize:11}}>⚠ আবশ্যক</div>}{form.has_license==="yes"&&<UB icon="🪪" color="#1d4ed8" bg="#eff6ff" border="#93c5fd" bn="লাইসেন্সের ছবি *" ar="صورة الرخصة *" file={form.licenseFile} onChange={e=>set("licenseFile",e.target.files[0])} accept="image/*"/>}</div>);}
function S4({form,set,errors}){const isIn=form.location==="inside_ksa";const isOut=form.location==="outside_bangladesh"||form.location==="outside_other";return(<div style={s.fields}><UB icon="📷" color="#E8712B" bg="#fff7ed" border="#fed7aa" bn="মুখের ছবি *" ar="صورة شخصية *" hint="সামনের দিকে, ভালো আলোতে" file={form.photoFile} onChange={e=>set("photoFile",e.target.files[0])} accept="image/*" error={errors.photoFile}/>{isIn&&<UB icon="🪪" color="#1d4ed8" bg="#eff6ff" border="#93c5fd" bn="ইকামার ছবি *" ar="صورة الإقامة *" file={form.iqamaFile} onChange={e=>set("iqamaFile",e.target.files[0])} accept="image/*" error={errors.iqamaFile}/>}{isOut&&<UB icon="📗" color="#2E7D32" bg="#f0fdf4" border="#86efac" bn="পাসপোর্টের ছবি *" ar="صورة جواز السفر *" file={form.passportFile} onChange={e=>set("passportFile",e.target.files[0])} accept="image/*" error={errors.passportFile}/>}{!form.location&&<div style={{background:"#fffbeb",border:"1px solid #fcd34d",borderRadius:12,padding:"10px 14px",color:"#92400e",fontSize:12}}>⚠️ প্রথমে আপনার অবস্থান নির্বাচন করুন</div>}</div>);}
function S5({form,set,errors}){return(<div style={s.fields}><div><div style={s.lbl}>ধাপে ধাপে গাড়ি ধোয়ার পদ্ধতি বলুন <span style={{color:"#E8712B"}}>*</span></div><div style={s.lbl2}>اشرح كيف تغسل سيارة خطوة بخطوة</div><textarea rows={5} value={form.car_wash_description} onChange={e=>set("car_wash_description",e.target.value)} placeholder="১. প্রথমে..." style={{...s.inp,...s.ta,...(errors.car_wash_description?s.err:{})}}/></div><div style={{background:"#fffbeb",border:"2px dashed #fcd34d",borderRadius:16,padding:"16px 14px",display:"flex",flexDirection:"column",alignItems:"center",gap:8}}><div style={{fontSize:36}}>🎥</div><div style={{color:"#92400e",fontSize:13,fontWeight:800}}>মোটরসাইকেল চালানোর ভিডিও *</div><div style={{color:"#78350f",fontSize:11,textAlign:"center"}}>৬০-৯০ সেকেন্ড — সর্বোচ্চ ১০০MB</div><label style={{display:"flex",alignItems:"center",justifyContent:"center",padding:"10px 16px",border:"2px dashed #f59e0b",borderRadius:12,fontSize:12,fontWeight:700,cursor:"pointer",color:"#92400e",width:"100%",boxSizing:"border-box"}}><span>{form.videoFile?`✅ ${form.videoFile.name}`:"ভিডিও বেছে নিন"}</span><input type="file" accept="video/*" onChange={e=>set("videoFile",e.target.files[0])} style={{display:"none"}}/></label>{errors.videoFile&&<div style={{color:"#dc2626",fontSize:11}}>⚠ আবশ্যক</div>}</div></div>);}
function S6({form,set,errors}){const Q=[{k:"q1",n:1,bn:"গ্রাহক সেবা নিতে অস্বীকার করলে কী করবেন?",ar:"لو رفض عميل الخدمة فجأة — ماذا ستفعل؟"},{k:"q2",n:2,bn:"গ্রাহক অ্যাপের বাইরে অতিরিক্ত জিনিস চাইলে?",ar:"عميل طلب فواحة أو مناديل خارج الطلب — كيف تتصرف؟"},{k:"q3",n:3,bn:"আগের চাকরি কেন ছেড়েছেন?",ar:"لماذا تركت عملك السابق؟"},{k:"q4",n:4,bn:"অভিযোগে বেতন কাটলে কী করবেন?",ar:"لو خُصم من راتبك بسبب شكوى عميل — كيف ستتصرف؟"},{k:"q5",n:5,bn:"এক বছর পর আপনার লক্ষ্য কী?",ar:"ما هدفك بعد سنة من العمل معنا؟"},{k:"q6",n:6,bn:"দেরিকারী সহকর্মীর সাথে কীভাবে আচরণ করবেন?",ar:"كيف تتعامل مع زميل يتأخر ويؤثر على الفريق؟"}];return(<div style={s.fields}><div style={{background:"#fffbeb",border:"1px solid #fcd34d",borderRadius:12,padding:"10px 14px",color:"#92400e",fontSize:12,fontWeight:700}}>💡 সঠিক বা ভুল উত্তর নেই — যা আসলে করবেন তা লিখুন</div>{Q.map(q=><div key={q.k} style={{display:"flex",gap:10}}><div style={{width:26,height:26,borderRadius:"50%",background:"linear-gradient(135deg,#E8712B,#f5a35f)",color:"#fff",fontSize:12,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,marginTop:2}}>{q.n}</div><div style={{flex:1}}><div style={{color:"#1e293b",fontSize:12,fontWeight:700,lineHeight:1.5}}>{q.bn}</div><div style={{color:"#a8834f",fontSize:11,marginTop:2,marginBottom:6}}>{q.ar}</div><textarea rows={2} value={form[q.k]} onChange={e=>set(q.k,e.target.value)} style={{...s.inp,...s.ta,...(errors[q.k]?s.err:{})}}/></div></div>)}</div>);}
function S7({form,set,errors}){
  const geo=form.bangladesh_district?calcGeoScore(form.bangladesh_district):null;
  return(<div style={s.fields}>
    {geo&&<div style={{background:ZONE_COLORS[geo.zone].bg,border:`1.5px solid ${ZONE_COLORS[geo.zone].border}`,borderRadius:12,padding:"10px 14px"}}><div style={{color:ZONE_COLORS[geo.zone].text,fontSize:12,fontWeight:800}}>{ZONE_COLORS[geo.zone].label}</div><div style={{color:ZONE_COLORS[geo.zone].text,fontSize:11}}>{form.bangladesh_district} — {form.bangladesh_city} | স্কোর: {geo.score}/100</div></div>}
    <div style={{background:"#f8fafc",border:"1.5px solid #e2e8f0",borderRadius:14,padding:20}}><div style={{color:"#1e293b",fontSize:14,fontWeight:800,marginBottom:14}}>নিশ্চিতকরণ</div><label style={{display:"flex",gap:12,cursor:"pointer",alignItems:"flex-start"}}><input type="checkbox" checked={form.declaration} onChange={e=>set("declaration",e.target.checked)} style={{width:20,height:20,marginTop:2,accentColor:"#E8712B",flexShrink:0}}/><div><p style={{color:"#1e293b",fontSize:13,fontWeight:600,marginBottom:6}}>✅ আমি নিশ্চিত করছি সব তথ্য সঠিক এবং হোয়াটসঅ্যাপে যোগাযোগে সম্মত।</p><p style={{color:"#a8834f",fontSize:12,marginBottom:8}}>أقر بأن جميع المعلومات صحيحة وأوافق على التواصل عبر الواتساب.</p><p style={{color:"#dc2626",fontSize:12,fontWeight:700}}>⚠️ ভুয়া তথ্য দিলে সাথে সাথে বাতিল করা হবে।</p></div></label>{errors.declaration&&<div style={{color:"#dc2626",fontSize:11,marginTop:8}}>⚠ চালিয়ে যেতে সম্মত হতে হবে</div>}</div>
  </div>);}
function UB({icon,color,bg,border,bn,ar,hint,file,onChange,accept,error}){return(<div style={{background:bg,border:`2px dashed ${border}`,borderRadius:16,padding:"14px",display:"flex",flexDirection:"column",alignItems:"center",gap:8}}><div style={{fontSize:30}}>{icon}</div><div style={{textAlign:"center"}}><div style={{color,fontSize:13,fontWeight:800}}>{bn}</div><div style={{color,fontSize:11,opacity:0.75}}>{ar}</div>{hint&&<div style={{color:"#64748b",fontSize:10,marginTop:2}}>{hint}</div>}</div><label style={{display:"flex",alignItems:"center",justifyContent:"center",padding:"10px 16px",border:`2px dashed ${color}`,borderRadius:12,fontSize:12,fontWeight:700,cursor:"pointer",color,width:"100%",boxSizing:"border-box"}}><span>{file?`✅ ${file.name}`:"বেছে নিন"}</span><input type="file" accept={accept} onChange={onChange} style={{display:"none"}}/></label>{error&&<div style={{color:"#dc2626",fontSize:11}}>⚠ আবশ্যক</div>}</div>);}
const s={page:{minHeight:"100dvh",background:"linear-gradient(170deg,#FFF9F0 0%,#FFF3DC 55%,#FFEACC 100%)",display:"flex",flexDirection:"column",alignItems:"center",padding:"0 0 32px",fontFamily:"'Segoe UI',Tahoma,sans-serif",position:"relative"},bgO1:{position:"fixed",top:-120,right:-80,width:300,height:300,borderRadius:"50%",background:"radial-gradient(circle,rgba(232,113,43,0.12) 0%,transparent 70%)",pointerEvents:"none"},bgO2:{position:"fixed",bottom:-100,left:-60,width:250,height:250,borderRadius:"50%",background:"radial-gradient(circle,rgba(46,125,50,0.08) 0%,transparent 70%)",pointerEvents:"none"},card:{width:"100%",maxWidth:480,background:"rgba(255,255,255,0.97)",borderRadius:"0 0 28px 28px",boxShadow:"0 8px 40px rgba(232,113,43,0.12)"},hdr:{background:"linear-gradient(135deg,#E8712B,#f5a35f)",padding:"20px 24px",display:"flex",alignItems:"center",gap:14},logoM:{width:44,height:44,background:"rgba(255,255,255,0.2)",borderRadius:12,display:"flex",alignItems:"center",justifyContent:"center",fontSize:20,flexShrink:0},hAr:{color:"#fff",fontSize:16,fontWeight:900},hBn:{color:"rgba(255,255,255,0.8)",fontSize:11},fields:{display:"flex",flexDirection:"column",gap:14,paddingBottom:8},inp:{width:"100%",padding:"11px 14px",border:"1.5px solid #e2e8f0",borderRadius:12,fontSize:13,color:"#1e293b",outline:"none",background:"#fafaf9",boxSizing:"border-box",direction:"rtl",fontFamily:"inherit"},ta:{resize:"none",minHeight:70},err:{borderColor:"#dc2626",background:"#fff5f5"},lbl:{color:"#1e293b",fontSize:12,fontWeight:700,marginBottom:2},lbl2:{color:"#a8834f",fontSize:10,marginBottom:4}};
