import{useState,useEffect}from"react";import{supabase}from"./supabase";
export default function InterviewPage({sessionId}){
  const[session,setSession]=useState(null);const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);
  useEffect(()=>{load();},[sessionId]);
  const load=async()=>{const{data}=await supabase.from("interview_sessions").select("*,applicants(full_name,application_number)").eq("id",sessionId).single();if(data){setSession(data);const i={};data.questions.forEach((_,n)=>{i[n]="";});setAnswers(i);}setLoading(false);};
  const submit=async()=>{const un=session.questions.filter((_,i)=>!answers[i]?.trim());if(un.length>0){alert("সমস্ত প্রশ্নের উত্তর দিন");return;}setSubmitting(true);
    try{const obj={};Object.keys(answers).forEach(k=>{obj[k]=answers[k];});
      await supabase.from("interview_sessions").update({answers:obj,status:"completed",completed_at:new Date().toISOString()}).eq("id",sessionId);
      await supabase.from("applicants").update({interview_answers:obj,interview_completed_at:new Date().toISOString(),status:"interview"}).eq("id",session.applicant_id);
      setSubmitted(true);}catch(err){alert("ত্রুটি: "+err.message);}setSubmitting(false);};
  if(loading)return <div style={{minHeight:"100dvh",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:40,height:40,border:"3px solid #fde4c4",borderTopColor:"#E8712B",borderRadius:"50%",animation:"spin 0.8s linear infinite"}}/></div>;
  if(!session)return <div style={{minHeight:"100dvh",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"sans-serif"}}><div style={{textAlign:"center"}}><div style={{fontSize:48}}>⚠️</div><p style={{color:"#dc2626",fontWeight:700}}>লিংকটি সঠিক নয়</p></div></div>;
  if(submitted||session.status==="completed")return(<div style={{minHeight:"100dvh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",fontFamily:"sans-serif",padding:32,textAlign:"center"}}><div style={{width:72,height:72,background:"linear-gradient(135deg,#2E7D32,#1b5e20)",borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontSize:32,fontWeight:900,margin:"0 auto 16px"}}>✓</div><h2 style={{color:"#1e293b",marginBottom:8}}>ধন্যবাদ!</h2><p style={{color:"#475569",fontSize:13}}>আপনার উত্তরগুলো সংরক্ষিত হয়েছে।</p></div>);
  return(<div style={{minHeight:"100dvh",background:"linear-gradient(170deg,#FFF9F0,#FFF3DC)",fontFamily:"'Segoe UI',Tahoma,sans-serif",direction:"rtl"}}><div style={{background:"linear-gradient(135deg,#E8712B,#f5a35f)",padding:"20px",position:"sticky",top:0,zIndex:100}}><div style={{color:"#fff",fontSize:18,fontWeight:900}}>{session.applicants?.full_name}</div><div style={{color:"rgba(255,255,255,0.85)",fontSize:11}}>সাক্ষাৎকার প্রশ্ন — আবেদন #{session.applicants?.application_number}</div></div><div style={{padding:16,display:"flex",flexDirection:"column",gap:14,maxWidth:600,margin:"0 auto"}}><div style={{background:"#fff7ed",border:"1px solid #fed7aa",borderRadius:12,padding:"10px 14px",color:"#92400e",fontSize:12,fontWeight:700}}>💡 যেকোনো ভাষায় উত্তর দিন<br/><span style={{fontSize:11,color:"#a8834f",fontWeight:400}}>أجب بأي لغة تريحك</span></div>{session.questions.map((q,i)=><div key={i} style={{background:"#fff",borderRadius:16,padding:"14px",boxShadow:"0 1px 6px rgba(0,0,0,0.06)"}}><div style={{display:"flex",gap:12,alignItems:"flex-start",marginBottom:10}}><div style={{width:28,height:28,borderRadius:"50%",background:"linear-gradient(135deg,#E8712B,#f5a35f)",color:"#fff",fontSize:13,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{i+1}</div><div>{q.bn&&<div style={{color:"#1e293b",fontSize:13,fontWeight:700,lineHeight:1.5}}>{q.bn}</div>}<div style={{color:"#a8834f",fontSize:11,marginTop:3}}>{q.ar}</div></div></div><textarea rows={3} value={answers[i]||""} onChange={e=>setAnswers(p=>({...p,[i]:e.target.value}))} placeholder="এখানে লিখুন..." style={{width:"100%",padding:"10px 14px",border:"1.5px solid #fde4c4",borderRadius:10,fontSize:13,outline:"none",resize:"vertical",fontFamily:"inherit",direction:"rtl",boxSizing:"border-box"}}/></div>)}<button onClick={submit} disabled={submitting} style={{width:"100%",padding:14,background:"linear-gradient(135deg,#2E7D32,#1b5e20)",border:"none",borderRadius:14,color:"#fff",fontSize:14,fontWeight:800,cursor:"pointer",marginBottom:32,opacity:submitting?0.6:1}}>{submitting?"পাঠানো হচ্ছে...":"উত্তর পাঠান ✓"}</button></div></div>);
}
