import{useState,useEffect}from"react";import{supabase}from"./supabase";import{ThemeToggle,Orbs}from"./ui";
export default function InterviewPage({sessionId}){
  const[session,setSession]=useState(null);const[answers,setAnswers]=useState({});const[submitted,setSubmitted]=useState(false);const[loading,setLoading]=useState(true);const[submitting,setSubmitting]=useState(false);
  useEffect(()=>{load();},[sessionId]);
  const load=async()=>{const{data}=await supabase.from("interview_sessions").select("*,applicants(full_name,application_number)").eq("id",sessionId).single();if(data){setSession(data);const i={};data.questions.forEach((_,n)=>{i[n]="";});setAnswers(i);}setLoading(false);};
  const submit=async()=>{const un=session.questions.filter((_,i)=>!answers[i]?.trim());if(un.length>0){alert("সমস্ত প্রশ্নের উত্তর দিন");return;}setSubmitting(true);
    try{const obj={};Object.keys(answers).forEach(k=>{obj[k]=answers[k];});
      await supabase.from("interview_sessions").update({answers:obj,status:"completed",completed_at:new Date().toISOString()}).eq("id",sessionId);
      await supabase.from("applicants").update({interview_answers:obj,interview_completed_at:new Date().toISOString(),status:"interview"}).eq("id",session.applicant_id);
      setSubmitted(true);}catch(err){alert("ত্রুটি: "+err.message);}setSubmitting(false);};
  if(loading)return <div className="g-iso" style={{minHeight:"100dvh",background:"var(--bg)",color:"var(--ink)",display:"flex",alignItems:"center",justifyContent:"center"}}><div className="g-spin" style={{width:40,height:40}}/></div>;
  if(!session)return <div className="g-iso" style={{minHeight:"100dvh",background:"var(--bg)",color:"var(--ink)",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"sans-serif"}}><div style={{textAlign:"center"}}><div style={{fontSize:48}}>⚠️</div><p style={{color:"var(--bad-ink)",fontWeight:700}}>লিংকটি সঠিক নয়</p></div></div>;
  if(submitted||session.status==="completed")return(<div className="g-iso" style={{minHeight:"100dvh",background:"var(--bg)",color:"var(--ink)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",fontFamily:"sans-serif",padding:32,textAlign:"center"}}><Orbs/><div className="g-corner"><ThemeToggle/></div><div style={{width:72,height:72,background:"linear-gradient(135deg,color-mix(in srgb,var(--ok) 80%,black),color-mix(in srgb,var(--ok) 60%,black))",borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",fontSize:32,fontWeight:900,margin:"0 auto 16px"}}>✓</div><h2 style={{color:"var(--ink)",marginBottom:8}}>ধন্যবাদ!</h2><p style={{color:"var(--ink-2)",fontSize:13}}>আপনার উত্তরগুলো সংরক্ষিত হয়েছে।</p></div>);
  return(<div className="g-iso" style={{minHeight:"100dvh",background:"var(--bg)",color:"var(--ink)",fontFamily:"system-ui,-apple-system,'Segoe UI','Noto Sans Bengali',Tahoma,sans-serif",direction:"rtl"}}><Orbs/><div style={{background:"linear-gradient(135deg,var(--a),var(--p))",padding:"20px",position:"sticky",top:0,zIndex:100}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><div><div style={{color:"#fff",fontSize:18,fontWeight:900}}>{session.applicants?.full_name}</div><div style={{color:"#fff",fontSize:11.5,fontWeight:600}}>সাক্ষাৎকার প্রশ্ন — আবেদন #{session.applicants?.application_number}</div></div><ThemeToggle/></div></div><div style={{padding:16,display:"flex",flexDirection:"column",gap:14,maxWidth:600,margin:"0 auto"}}><div style={{background:"var(--p-50)",border:"1px solid rgba(var(--p-rgb),.3)",borderRadius:12,padding:"10px 14px",color:"var(--warn-ink)",fontSize:12,fontWeight:700}}>💡 যেকোনো ভাষায় উত্তর দিন<br/><span style={{fontSize:11,color:"var(--mut)",fontWeight:400}}>أجب بأي لغة تريحك</span></div>{session.questions.map((q,i)=><div key={i} style={{background:"var(--glass-2)",borderRadius:16,padding:"14px",boxShadow:"0 1px 6px rgba(0,0,0,0.06)"}}><div style={{display:"flex",gap:12,alignItems:"flex-start",marginBottom:10}}><div style={{width:28,height:28,borderRadius:"50%",background:"linear-gradient(135deg,var(--a),var(--p))",color:"#fff",fontSize:13,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{i+1}</div><div>{q.bn&&<div style={{color:"var(--ink)",fontSize:13,fontWeight:700,lineHeight:1.5}}>{q.bn}</div>}<div style={{color:"var(--mut)",fontSize:11,marginTop:3}}>{q.ar}</div></div></div><textarea className="g-textarea" rows={3} value={answers[i]||""} onChange={e=>setAnswers(p=>({...p,[i]:e.target.value}))} placeholder="এখানে লিখুন..." style={{width:"100%",padding:"10px 14px",border:"1px solid var(--line-2)",borderRadius:10,fontSize:15,outline:"none",resize:"vertical",fontFamily:"inherit",direction:"rtl",boxSizing:"border-box"}}/></div>)}<button onClick={submit} disabled={submitting} style={{width:"100%",padding:14,background:"linear-gradient(135deg,color-mix(in srgb,var(--ok) 80%,black),color-mix(in srgb,var(--ok) 60%,black))",border:"none",borderRadius:14,color:"#fff",fontSize:14,fontWeight:800,cursor:"pointer",marginBottom:32,opacity:submitting?0.6:1}}>{submitting?"পাঠানো হচ্ছে...":"উত্তর পাঠান ✓"}</button></div></div>);
}
